name: PPI-HTML
version: 0.02
abstract: Generate syntax-hightlighted HTML for Perl using PPI
author: Adam Kennedy<cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
requires:
  perl: 5.005
  CSS::Tiny: 1.06
  PPI: 0.840
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
