---
abstract: 'Generate syntax-hightlighted HTML for Perl using PPI'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PPI-HTML
no_index:
  directory:
    - inc
    - t
requires:
  CSS::Tiny: 1.10
  PPI: 0.990
  Params::Util: 0.05
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/PPI-HTML
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/PPI-HTML
version: 1.08
